server {
    # Cloud Run default port
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # This is strictly required for React/Vite Router to work
        # It redirects all requests to index.html so the frontend handles routing
        try_files $uri $uri/ /index.html;
    }
}
